linters:
  enable:
    - errorlint
    - forcetypeassert
    - forbidigo
    - exhaustive
    - cyclop
    - gofmt
    - gosec
    - misspell
      # future - wrapcheck
    - whitespace
    - unconvert
