on:
  push:
    tags:
      - 'v*'

name: Build and release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://golang:1.16
        with:
          args: make all
          # apparently github auto-mounts dirs so no volumes needed
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "bin/*"
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true


